var hierarchy =
[
    [ "AccessTokenFailJson", "class_access_token_fail_json.html", null ],
    [ "AccessTokenResponseJson", "class_access_token_response_json.html", null ],
    [ "Action", "class_mirage_x_r_1_1_action.html", null ],
    [ "Action< string >", "class_mirage_x_r_1_1_action.html", null ],
    [ "Activity", "class_mirage_x_r_1_1_activity.html", null ],
    [ "ActivityRecorderServiceConfiguration", "class_mirage_x_r_1_1_activity_recorder_service_configuration.html", null ],
    [ "ActivitySelectionSceneReferenceServiceConfiguration", "class_activity_selection_scene_reference_service_configuration.html", null ],
    [ "WorkplaceManager.AnchorCalibrationPair", "struct_mirage_x_r_1_1_workplace_manager_1_1_anchor_calibration_pair.html", null ],
    [ "App", "class_mirage_x_r_1_1_app.html", null ],
    [ "SketchfabManager.AppCredentials", "class_mirage_x_r_1_1_sketchfab_manager_1_1_app_credentials.html", null ],
    [ "ArlemMessage", "class_mirage_x_r_1_1_arlem_message.html", null ],
    [ "AuthorizationCodeResponseJson", "class_authorization_code_response_json.html", null ],
    [ "BaseFocusHandler", "class_base_focus_handler.html", [
      [ "MirageXRPrefab", "class_mirage_x_r_1_1_mirage_x_r_prefab.html", [
        [ "ActionContentObject", "class_mirage_x_r_1_1_action_content_object.html", null ],
        [ "AudioPlayer", "class_mirage_x_r_1_1_audio_player.html", null ],
        [ "CharacterController", "class_mirage_x_r_1_1_character_controller.html", null ],
        [ "Detect", "class_mirage_x_r_1_1_detect.html", null ],
        [ "FloatingImageViewer", "class_mirage_x_r_1_1_floating_image_viewer.html", null ],
        [ "FloatingVideoViewer", "class_mirage_x_r_1_1_floating_video_viewer.html", null ],
        [ "GhostHandPlayer", "class_mirage_x_r_1_1_ghost_hand_player.html", null ],
        [ "GhosttrackPrefabPlayer", "class_mirage_x_r_1_1_ghosttrack_prefab_player.html", null ],
        [ "GlyphItems", "class_mirage_x_r_1_1_glyph_items.html", null ],
        [ "HandsPrefabPlayer", "class_mirage_x_r_1_1_hands_prefab_player.html", null ],
        [ "ImageMarkerController", "class_mirage_x_r_1_1_image_marker_controller.html", null ],
        [ "Label", "class_mirage_x_r_1_1_label.html", null ],
        [ "Model", "class_mirage_x_r_1_1_model.html", null ],
        [ "PickAndPlaceController", "class_mirage_x_r_1_1_pick_and_place_controller.html", null ],
        [ "PluginController", "class_mirage_x_r_1_1_plugin_controller.html", null ],
        [ "PostItLabel", "class_mirage_x_r_1_1_post_it_label.html", null ],
        [ "Potentiometer", "class_mirage_x_r_1_1_potentiometer.html", null ],
        [ "ShowCardsButton", "class_mirage_x_r_1_1_show_cards_button.html", null ],
        [ "Symbol", "class_mirage_x_r_1_1_symbol.html", null ],
        [ "UiSymbol", "class_mirage_x_r_1_1_ui_symbol.html", null ]
      ] ]
    ] ],
    [ "BaseServiceBootstrapper", "class_base_service_bootstrapper.html", [
      [ "ActivitySelectionBootstrapper", "class_activity_selection_bootstrapper.html", null ],
      [ "MirageXRServiceBootstrapper", "class_mirage_x_r_1_1_mirage_x_r_service_bootstrapper.html", null ]
    ] ],
    [ "BufferedBinaryReader.Bit2Converter", "struct_buffered_binary_reader_1_1_bit2_converter.html", null ],
    [ "BufferedBinaryReader.Bit4Converter", "struct_buffered_binary_reader_1_1_bit4_converter.html", null ],
    [ "Character", "class_mirage_x_r_1_1_character.html", null ],
    [ "ConfigEditor", "class_config_editor.html", null ],
    [ "Data", "class_mirage_x_r_1_1_data.html", null ],
    [ "DeepLinkDefinition", "class_deep_link_definition.html", null ],
    [ "DestinationPoints", "class_mirage_x_r_1_1_destination_points.html", null ],
    [ "Detectable", "class_mirage_x_r_1_1_detectable.html", null ],
    [ "Device", "class_mirage_x_r_1_1_device.html", null ],
    [ "DialogButtonContent", "class_dialog_button_content.html", null ],
    [ "EnterExit", "class_mirage_x_r_1_1_enter_exit.html", [
      [ "Enter", "class_mirage_x_r_1_1_enter.html", null ],
      [ "Exit", "class_mirage_x_r_1_1_exit.html", null ]
    ] ],
    [ "EventArgs", "class_event_args.html", [
      [ "TapEventArgs", "class_mirage_x_r_1_1_tap_event_args.html", null ]
    ] ],
    [ "FacebookResponse", "struct_facebook_response.html", null ],
    [ "GhostDataFrame", "struct_mirage_x_r_1_1_ghost_data_frame.html", null ],
    [ "GhostRecorder", "class_ghost_recorder.html", null ],
    [ "GltfArchive", "class_gltf_archive.html", null ],
    [ "HandsDataFrame", "class_mirage_x_r_1_1_hands_data_frame.html", null ],
    [ "HololensSensorDataFrame", "class_mirage_x_r_1_1_hololens_sensor_data_frame.html", null ],
    [ "IDisposable", "class_i_disposable.html", [
      [ "BufferedBinaryReader", "class_buffered_binary_reader.html", null ],
      [ "SessionDownloader", "class_mirage_x_r_1_1_session_downloader.html", null ]
    ] ],
    [ "IDragHandler", "class_i_drag_handler.html", [
      [ "PageView", "class_page_view.html", null ]
    ] ],
    [ "IEndDragHandler", "class_i_end_drag_handler.html", [
      [ "PageView", "class_page_view.html", null ]
    ] ],
    [ "IMixedRealityFocusHandler", "class_i_mixed_reality_focus_handler.html", [
      [ "TaskStationController", "class_mirage_x_r_1_1_task_station_controller.html", null ]
    ] ],
    [ "IMixedRealityGestureHandler", "class_i_mixed_reality_gesture_handler.html", [
      [ "MirageXRModelManipulation", "class_mirage_x_r_model_manipulation.html", null ]
    ] ],
    [ "IMixedRealityPointerHandler", "class_i_mixed_reality_pointer_handler.html", [
      [ "TapRecognizerService", "class_mirage_x_r_1_1_tap_recognizer_service.html", null ]
    ] ],
    [ "ImportTask", "class_import_task.html", null ],
    [ "Imuframe", "class_mirage_x_r_1_1_imuframe.html", null ],
    [ "Instruction", "class_mirage_x_r_1_1_instruction.html", null ],
    [ "IOidcProvider", "class_i_oidc_provider.html", null ],
    [ "IPointerDownHandler", "class_i_pointer_down_handler.html", [
      [ "VideoManager", "class_video_manager.html", null ]
    ] ],
    [ "IPointerEnterHandler", "class_i_pointer_enter_handler.html", [
      [ "HoverGuilde", "class_hover_guilde.html", null ],
      [ "Tappable", "class_tappable.html", null ]
    ] ],
    [ "IPointerExitHandler", "class_i_pointer_exit_handler.html", [
      [ "HoverGuilde", "class_hover_guilde.html", null ],
      [ "Tappable", "class_tappable.html", null ]
    ] ],
    [ "IPointerUpHandler", "class_i_pointer_up_handler.html", [
      [ "VideoManager", "class_video_manager.html", null ]
    ] ],
    [ "IService", "class_i_service.html", [
      [ "ActivitySelectionSceneReferenceService", "class_activity_selection_scene_reference_service.html", null ],
      [ "EditorSceneService", "class_editor_scene_service.html", null ],
      [ "ActivityRecorderService", "class_mirage_x_r_1_1_activity_recorder_service.html", null ],
      [ "ExperienceService", "class_mirage_x_r_1_1_experience_service.html", null ],
      [ "ITextToSpeechService", "interface_mirage_x_r_1_1_i_text_to_speech_service.html", [
        [ "HTKTextToSpeechService", "class_mirage_x_r_1_1_h_t_k_text_to_speech_service.html", null ]
      ] ],
      [ "KeywordService", "class_mirage_x_r_1_1_keyword_service.html", null ],
      [ "SpeechService", "class_mirage_x_r_1_1_speech_service.html", null ],
      [ "TapRecognizerService", "class_mirage_x_r_1_1_tap_recognizer_service.html", null ],
      [ "VestService", "class_mirage_x_r_1_1_vest_service.html", null ],
      [ "WorldAnchorService", "class_mirage_x_r_1_1_world_anchor_service.html", null ],
      [ "VideoAudioTrackGlobalService", "class_video_audio_track_global_service.html", null ]
    ] ],
    [ "IUserInfo", "class_i_user_info.html", null ],
    [ "JsonConverter", "class_json_converter.html", null ],
    [ "ListView< T >", "class_mirage_x_r_1_1_list_view.html", null ],
    [ "ListView< MirageXR.SessionContainer >", "class_mirage_x_r_1_1_list_view.html", null ],
    [ "ListViewItem< SessionContainer >", "class_mirage_x_r_1_1_list_view_item.html", [
      [ "SessionContainerListItem", "class_mirage_x_r_1_1_session_container_list_item.html", null ]
    ] ],
    [ "MaggieManager", "class_maggie_manager.html", null ],
    [ "MaskableGraphic", "class_maskable_graphic.html", null ],
    [ "Message", "class_mirage_x_r_1_1_message.html", null ],
    [ "ModelArchive", "class_model_archive.html", null ],
    [ "ModelCategory", "class_model_category.html", null ],
    [ "ModelDownloadInfo", "class_model_download_info.html", null ],
    [ "ModelInfo", "class_model_info.html", null ],
    [ "ModelPreviewItem", "class_model_preview_item.html", null ],
    [ "ModelTag", "class_model_tag.html", null ],
    [ "ModelThumbnails", "class_model_thumbnails.html", null ],
    [ "MonoBehaviour", null, [
      [ "ActionController", "class_action_controller.html", null ],
      [ "ActionDetailView", "class_action_detail_view.html", null ],
      [ "ActionEditor", "class_action_editor.html", null ],
      [ "ActionListItem", "class_action_list_item.html", null ],
      [ "ActionListMenu", "class_action_list_menu.html", null ],
      [ "ActivityEditor", "class_activity_editor.html", null ],
      [ "AmbientLighting", "class_ambient_lighting.html", null ],
      [ "AnnotationEditor", "class_annotation_editor.html", null ],
      [ "AnnotationListItem", "class_annotation_list_item.html", null ],
      [ "AppSelection", "class_app_selection.html", null ],
      [ "AppStart", "class_app_start.html", null ],
      [ "ARFeatheredPlaneMeshVisualizer", "class_a_r_feathered_plane_mesh_visualizer.html", null ],
      [ "ARManager", "class_a_r_manager.html", null ],
      [ "AudioEditor", "class_audio_editor.html", null ],
      [ "BrandCustomizer", "class_brand_customizer.html", null ],
      [ "ButtonHandler", "class_button_handler.html", null ],
      [ "CharacterListItem", "class_character_list_item.html", null ],
      [ "ContentListItem", "class_content_list_item.html", null ],
      [ "ContentListView", "class_content_list_view.html", null ],
      [ "ContentSelectorListItem", "class_content_selector_list_item.html", null ],
      [ "CropHandeler", "class_crop_handeler.html", null ],
      [ "DestroyAfterSec", "class_destroy_after_sec.html", null ],
      [ "DeviceMqttBehaviour", "class_device_mqtt_behaviour.html", null ],
      [ "DialogWindow", "class_dialog_window.html", null ],
      [ "DummyLogic", "class_dummy_logic.html", null ],
      [ "EyeBlink", "class_eye_blink.html", null ],
      [ "FindMeInScene", "class_find_me_in_scene.html", null ],
      [ "GhosttrackEditor", "class_ghosttrack_editor.html", null ],
      [ "GlobalKeywords", "class_global_keywords.html", null ],
      [ "GlyphListItem", "class_glyph_list_item.html", null ],
      [ "HomePathVisibilityController", "class_home_path_visibility_controller.html", null ],
      [ "HoverGuilde", "class_hover_guilde.html", null ],
      [ "ImageEditor", "class_image_editor.html", null ],
      [ "ImageMarkerEditor", "class_image_marker_editor.html", null ],
      [ "KeepBetweenScenes", "class_keep_between_scenes.html", null ],
      [ "LoadView", "class_load_view.html", null ],
      [ "MaterialTilingFromLineLength", "class_material_tiling_from_line_length.html", null ],
      [ "ActionContentStorageManager", "class_mirage_x_r_1_1_action_content_storage_manager.html", null ],
      [ "ActivityCard", "class_mirage_x_r_1_1_activity_card.html", null ],
      [ "ActivityCardManager", "class_mirage_x_r_1_1_activity_card_manager.html", null ],
      [ "ActivityFilter", "class_mirage_x_r_1_1_activity_filter.html", null ],
      [ "ActivityListItem", "class_mirage_x_r_1_1_activity_list_item.html", null ],
      [ "ActivityListView", "class_mirage_x_r_1_1_activity_list_view.html", null ],
      [ "ActivityManager", "class_mirage_x_r_1_1_activity_manager.html", null ],
      [ "ActivitySelection", "class_mirage_x_r_1_1_activity_selection.html", null ],
      [ "ActivitySelectionMenu", "class_mirage_x_r_1_1_activity_selection_menu.html", null ],
      [ "ActivitySelector", "class_mirage_x_r_1_1_activity_selector.html", null ],
      [ "AppSelectionExitHandler", "class_mirage_x_r_1_1_app_selection_exit_handler.html", null ],
      [ "ArlemDownload", "class_mirage_x_r_1_1_arlem_download.html", null ],
      [ "ArlemFetcher", "class_mirage_x_r_1_1_arlem_fetcher.html", null ],
      [ "Arrow", "class_mirage_x_r_1_1_arrow.html", null ],
      [ "BrandManager", "class_mirage_x_r_1_1_brand_manager.html", null ],
      [ "ButtonManager", "class_mirage_x_r_1_1_button_manager.html", null ],
      [ "CalibrationMarker", "class_mirage_x_r_1_1_calibration_marker.html", null ],
      [ "CalibrationTool", "class_mirage_x_r_1_1_calibration_tool.html", null ],
      [ "CharacterAugmentation", "class_mirage_x_r_1_1_character_augmentation.html", null ],
      [ "CharacterSettings", "class_mirage_x_r_1_1_character_settings.html", null ],
      [ "Click", "class_mirage_x_r_1_1_click.html", null ],
      [ "ContainerBehaviour", "class_mirage_x_r_1_1_container_behaviour.html", null ],
      [ "DebugManager", "class_mirage_x_r_1_1_debug_manager.html", null ],
      [ "Destination", "class_mirage_x_r_1_1_destination.html", null ],
      [ "DetectableBehaviour", "class_mirage_x_r_1_1_detectable_behaviour.html", null ],
      [ "DialogRecorder", "class_mirage_x_r_1_1_dialog_recorder.html", null ],
      [ "EventManager", "class_mirage_x_r_1_1_event_manager.html", null ],
      [ "FakeFloor", "class_mirage_x_r_1_1_fake_floor.html", null ],
      [ "GazeGuide", "class_mirage_x_r_1_1_gaze_guide.html", null ],
      [ "GazeSpinner", "class_mirage_x_r_1_1_gaze_spinner.html", null ],
      [ "GhostRecordPlayer", "class_mirage_x_r_1_1_ghost_record_player.html", null ],
      [ "GlyphEditor", "class_mirage_x_r_1_1_glyph_editor.html", null ],
      [ "HumEnvMqttBehaviour", "class_mirage_x_r_1_1_hum_env_mqtt_behaviour.html", null ],
      [ "LabelEditor", "class_mirage_x_r_1_1_label_editor.html", null ],
      [ "ListViewItem< T >", "class_mirage_x_r_1_1_list_view_item.html", null ],
      [ "LockZAxis", "class_mirage_x_r_1_1_lock_z_axis.html", null ],
      [ "Login", "class_mirage_x_r_1_1_login.html", null ],
      [ "Maggie", "class_mirage_x_r_1_1_maggie.html", null ],
      [ "MeasureTool", "class_mirage_x_r_1_1_measure_tool.html", null ],
      [ "ModelEditor", "class_mirage_x_r_1_1_model_editor.html", null ],
      [ "ModelManager", "class_mirage_x_r_1_1_model_manager.html", null ],
      [ "MoodleManager", "class_mirage_x_r_1_1_moodle_manager.html", null ],
      [ "MovementManager", "class_mirage_x_r_1_1_movement_manager.html", null ],
      [ "NonHeadsetUIController", "class_mirage_x_r_1_1_non_headset_u_i_controller.html", null ],
      [ "ObjectFactory", "class_mirage_x_r_1_1_object_factory.html", null ],
      [ "PathSegmentsController", "class_mirage_x_r_1_1_path_segments_controller.html", null ],
      [ "PersonBehaviour", "class_mirage_x_r_1_1_person_behaviour.html", null ],
      [ "Pick", "class_mirage_x_r_1_1_pick.html", null ],
      [ "PlaceBehaviour", "class_mirage_x_r_1_1_place_behaviour.html", null ],
      [ "PlatformManager", "class_mirage_x_r_1_1_platform_manager.html", null ],
      [ "PlayerExitHandler", "class_mirage_x_r_1_1_player_exit_handler.html", null ],
      [ "PluginEditor", "class_mirage_x_r_1_1_plugin_editor.html", null ],
      [ "ProgressManager", "class_mirage_x_r_1_1_progress_manager.html", null ],
      [ "RealTimeSensorManager", "class_mirage_x_r_1_1_real_time_sensor_manager.html", null ],
      [ "RotationMachine", "class_mirage_x_r_1_1_rotation_machine.html", null ],
      [ "ScrollableListPopulator", "class_mirage_x_r_1_1_scrollable_list_populator.html", null ],
      [ "SensorBase", "class_mirage_x_r_1_1_sensor_base.html", [
        [ "HololensSensors", "class_mirage_x_r_1_1_hololens_sensors.html", null ]
      ] ],
      [ "SensorContainer", "class_mirage_x_r_1_1_sensor_container.html", null ],
      [ "SensorDisplay", "class_mirage_x_r_1_1_sensor_display.html", null ],
      [ "SensorValueDisplay", "class_mirage_x_r_1_1_sensor_value_display.html", null ],
      [ "SessionButton", "class_mirage_x_r_1_1_session_button.html", null ],
      [ "SessionListView", "class_mirage_x_r_1_1_session_list_view.html", null ],
      [ "SketchfabManager", "class_mirage_x_r_1_1_sketchfab_manager.html", null ],
      [ "SmartRotationController", "class_mirage_x_r_1_1_smart_rotation_controller.html", null ],
      [ "SmartTrigger", "class_mirage_x_r_1_1_smart_trigger.html", null ],
      [ "SpriteToggle", "class_mirage_x_r_1_1_sprite_toggle.html", null ],
      [ "StaticImageViewer", "class_mirage_x_r_1_1_static_image_viewer.html", null ],
      [ "StaticVideoPlayer", "class_mirage_x_r_1_1_static_video_player.html", null ],
      [ "SystemSounds", "class_mirage_x_r_1_1_system_sounds.html", null ],
      [ "TaskStationController", "class_mirage_x_r_1_1_task_station_controller.html", null ],
      [ "TaskStationDetailMenu", "class_mirage_x_r_1_1_task_station_detail_menu.html", null ],
      [ "TaskStationStateController", "class_mirage_x_r_1_1_task_station_state_controller.html", null ],
      [ "TaskStep", "class_mirage_x_r_1_1_task_step.html", null ],
      [ "TermsOfUse", "class_mirage_x_r_1_1_terms_of_use.html", null ],
      [ "ThingBehaviour", "class_mirage_x_r_1_1_thing_behaviour.html", null ],
      [ "TimelineObjectBehaviour", "class_mirage_x_r_1_1_timeline_object_behaviour.html", null ],
      [ "TutorialButton", "class_mirage_x_r_1_1_tutorial_button.html", null ],
      [ "TutorialManager", "class_mirage_x_r_1_1_tutorial_manager.html", null ],
      [ "UiManager", "class_mirage_x_r_1_1_ui_manager.html", null ],
      [ "VFXEditor", "class_mirage_x_r_1_1_v_f_x_editor.html", null ],
      [ "VoiceTrigger", "class_mirage_x_r_1_1_voice_trigger.html", null ],
      [ "WaitSpinner", "class_mirage_x_r_1_1_wait_spinner.html", null ],
      [ "WindowMovement", "class_mirage_x_r_1_1_window_movement.html", null ],
      [ "WorkplaceManager", "class_mirage_x_r_1_1_workplace_manager.html", null ],
      [ "MirageXRLearningHubControl", "class_mirage_x_r_learning_hub_control.html", null ],
      [ "MirageXRModelAnnotationEditor", "class_mirage_x_r_model_annotation_editor.html", null ],
      [ "MirageXRModelExpander", "class_mirage_x_r_model_expander.html", null ],
      [ "MirageXRModelManipulation", "class_mirage_x_r_model_manipulation.html", null ],
      [ "MirageXRVideoAnnotationEditor", "class_mirage_x_r_video_annotation_editor.html", null ],
      [ "MixedRealityInputField", "class_mixed_reality_input_field.html", null ],
      [ "ModelListItem", "class_model_list_item.html", null ],
      [ "NativeCameraTest", "class_native_camera_test.html", null ],
      [ "OAuthClient", "class_o_auth_client.html", null ],
      [ "PageView", "class_page_view.html", null ],
      [ "PathRoleController", "class_path_role_controller.html", null ],
      [ "PickAndPlaceEditor", "class_pick_and_place_editor.html", null ],
      [ "PlayerStart", "class_player_start.html", null ],
      [ "PlayerTimeStamper", "class_player_time_stamper.html", null ],
      [ "PluginListItem", "class_plugin_list_item.html", null ],
      [ "PoiAddItem", "class_poi_add_item.html", null ],
      [ "PoiEditor", "class_poi_editor.html", null ],
      [ "PopupBase", "class_popup_base.html", [
        [ "CalibrationGuideView", "class_calibration_guide_view.html", null ],
        [ "ContentHintView", "class_content_hint_view.html", null ],
        [ "ContentSelectorView", "class_content_selector_view.html", null ],
        [ "LoginView", "class_login_view.html", null ],
        [ "PopupEditorBase", "class_popup_editor_base.html", [
          [ "AudioEditorView", "class_audio_editor_view.html", null ],
          [ "CharacterEditorView", "class_character_editor_view.html", null ],
          [ "GhostEditorView", "class_ghost_editor_view.html", null ],
          [ "GlyphEditorView", "class_glyph_editor_view.html", null ],
          [ "ImageEditorView", "class_image_editor_view.html", null ],
          [ "ImageMarkerEditorView", "class_image_marker_editor_view.html", null ],
          [ "LabelEditorView", "class_label_editor_view.html", null ],
          [ "ModelEditorView", "class_model_editor_view.html", null ],
          [ "PickAndPlaceEditorView", "class_pick_and_place_editor_view.html", null ],
          [ "PluginEditorView", "class_plugin_editor_view.html", null ],
          [ "VfxEditorView", "class_vfx_editor_view.html", null ],
          [ "VideoEditorView", "class_video_editor_view.html", null ]
        ] ],
        [ "SettingsView", "class_settings_view.html", null ],
        [ "ThumbnailEditorView", "class_thumbnail_editor_view.html", null ]
      ] ],
      [ "PopupsViewer", "class_popups_viewer.html", null ],
      [ "ProcessDeepLinkMngr", "class_process_deep_link_mngr.html", null ],
      [ "ProgressBarController", "class_progress_bar_controller.html", null ],
      [ "RecordTestController", "class_record_test_controller.html", null ],
      [ "RootView", "class_root_view.html", null ],
      [ "SelectObjectPannelHandler", "class_select_object_pannel_handler.html", null ],
      [ "SetPoints", "class_set_points.html", null ],
      [ "SetStartingPosition", "class_set_starting_position.html", null ],
      [ "SettingsInputField", "class_settings_input_field.html", null ],
      [ "SplashPlayer", "class_splash_player.html", null ],
      [ "StepsListItem", "class_steps_list_item.html", null ],
      [ "StepsListView", "class_steps_list_view.html", null ],
      [ "StringListItem", "class_string_list_item.html", null ],
      [ "TagLock", "class_tag_lock.html", null ],
      [ "Tappable", "class_tappable.html", null ],
      [ "TaskStationEditor", "class_task_station_editor.html", null ],
      [ "ThreeLSControl", "class_three_l_s_control.html", null ],
      [ "Toast", "class_toast.html", null ],
      [ "TrackableEventHandlerEvents", "class_trackable_event_handler_events.html", null ],
      [ "TurnToCamera", "class_turn_to_camera.html", null ],
      [ "UIOrigin", "class_u_i_origin.html", null ],
      [ "UnitTestManager", "class_unit_test_manager.html", null ],
      [ "UserViewportController", "class_user_viewport_controller.html", null ],
      [ "VfxListItem", "class_vfx_list_item.html", null ],
      [ "VideoEditor", "class_video_editor.html", null ],
      [ "VideoManager", "class_video_manager.html", null ],
      [ "WearableManager", "class_wearable_manager.html", null ]
    ] ],
    [ "NativeCameraController", "class_native_camera_controller.html", null ],
    [ "Person", "class_mirage_x_r_1_1_person.html", null ],
    [ "Place", "class_mirage_x_r_1_1_place.html", null ],
    [ "PluginEditor.Plugin", "struct_mirage_x_r_1_1_plugin_editor_1_1_plugin.html", null ],
    [ "Poi", "class_mirage_x_r_1_1_poi.html", null ],
    [ "Point", "class_mirage_x_r_1_1_point.html", null ],
    [ "Positions", "class_mirage_x_r_1_1_positions.html", null ],
    [ "PrefsBoolValue", "class_mirage_x_r_1_1_prefs_bool_value.html", null ],
    [ "PrefsStringValue", "class_mirage_x_r_1_1_prefs_string_value.html", null ],
    [ "Primitive", "class_mirage_x_r_1_1_primitive.html", null ],
    [ "SaveLoadAudioUtilities", "class_save_load_audio_utilities.html", null ],
    [ "ScriptableObject", "class_scriptable_object.html", [
      [ "ActionObject", "class_action_object.html", null ],
      [ "CharacterObject", "class_character_object.html", null ],
      [ "ExperienceAPIClientCredentials", "class_mirage_x_r_1_1_experience_a_p_i_client_credentials.html", null ],
      [ "PluginObject", "class_plugin_object.html", null ],
      [ "VfxObject", "class_vfx_object.html", null ]
    ] ],
    [ "SearchCursor", "class_search_cursor.html", null ],
    [ "Sensor", "class_mirage_x_r_1_1_sensor.html", null ],
    [ "SensorDataFrame", "class_mirage_x_r_1_1_sensor_data_frame.html", null ],
    [ "DeviceMqttBehaviour.SensorVariable", "class_device_mqtt_behaviour_1_1_sensor_variable.html", null ],
    [ "Session", "class_session.html", null ],
    [ "SessionContainer", "class_mirage_x_r_1_1_session_container.html", null ],
    [ "SketchfabCollection", "class_sketchfab_collection.html", null ],
    [ "SketchfabCollectionSearchResult", "class_sketchfab_collection_search_result.html", null ],
    [ "SketchfabModel", "class_sketchfab_model.html", null ],
    [ "SketchfabModelSearchResult", "class_sketchfab_model_search_result.html", null ],
    [ "SketchfabUser", "class_sketchfab_user.html", null ],
    [ "SketchfabUserSearchResult", "class_sketchfab_user_search_result.html", null ],
    [ "SpatialMappingHelper", "class_mirage_x_r_1_1_spatial_mapping_helper.html", null ],
    [ "StepSettings", "class_mirage_x_r_1_1_step_settings.html", null ],
    [ "ActivitySelector.StoredFile", "struct_mirage_x_r_1_1_activity_selector_1_1_stored_file.html", null ],
    [ "Thing", "class_mirage_x_r_1_1_thing.html", null ],
    [ "ThumbnailImage", "class_thumbnail_image.html", null ],
    [ "ToggleObject", "class_mirage_x_r_1_1_toggle_object.html", [
      [ "Activate", "class_mirage_x_r_1_1_activate.html", null ],
      [ "Deactivate", "class_mirage_x_r_1_1_deactivate.html", null ]
    ] ],
    [ "Trigger", "class_mirage_x_r_1_1_trigger.html", null ],
    [ "Tutorial", "class_mirage_x_r_1_1_tutorial.html", null ],
    [ "UserAvatar", "class_user_avatar.html", null ],
    [ "UserAvatarImages", "class_user_avatar_images.html", null ],
    [ "UserInfoResponseJson", "class_user_info_response_json.html", null ],
    [ "VestDataFrame", "class_mirage_x_r_1_1_vest_data_frame.html", null ],
    [ "VestServiceConfiguration", "class_mirage_x_r_1_1_vest_service_configuration.html", null ],
    [ "Workplace", "class_mirage_x_r_1_1_workplace.html", null ],
    [ "UnityEvent", null, [
      [ "PageView.IntUnityEvent", "class_page_view_1_1_int_unity_event.html", null ],
      [ "TextChangedEvent", "class_text_changed_event.html", null ]
    ] ]
];